######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 15 21:18:10 2011
######################################################################

TEMPLATE = app
TARGET = qt_svg
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl svg

# Input
SOURCES += main.cpp
RESOURCES = qt_svg.qrc
